/**
 * Music jokes, puns, and facts shown during song generation.
 * ~150 items so users rarely see repeats.
 */
export const musicFacts: string[] = [
  // Puns & jokes
  "Why did the musician get arrested? Because she got caught in a treble situation.",
  "What do you call a cow that plays guitar? A moo-sician.",
  "Why couldn't the string quartet find their composer? He was Haydn.",
  "What's a skeleton's favourite instrument? The trom-bone.",
  "I wrote a song about a tortilla. Actually, it's more of a wrap.",
  "What do you get when you drop a piano down a mine shaft? A flat minor.",
  "Why did the pianist keep banging his head against the keys? He was playing by ear.",
  "What's the difference between a guitar and a fish? You can tune a guitar but you can't tuna fish.",
  "What do you call a musical insect? A humbug.",
  "Why are pirates such good singers? They can hit the high Cs.",
  "What type of music are balloons scared of? Pop music.",
  "What's a cat's favourite song? Three Blind Mice.",
  "What makes music on your head? A headband.",
  "What do you call clean music? A soap opera.",
  "Why did the chicken join the band? Because it had the drumsticks.",
  "What's Beethoven's favourite fruit? Ba-na-na-naaaa.",
  "What do you call a laughing piano? A Yamahahaha.",
  "Why do fluorescent lights hum? Because they don't know the lyrics.",
  "What do you call a guitar that never finishes a song? A quitar.",
  "Where did the music teacher leave her keys? In the piano.",
  "What's the most musical part of a turkey? The drumstick.",
  "Why was the musician so calm? She knew how to compose herself.",
  "What do you call a musical Christmas tree? Spruce Springsteen.",
  "Why can't you play music at a fishing tournament? You might drop the bass.",
  "What do you call an elf who sings? A wrapper.",
  "How do you fix a broken tuba? With a tuba glue.",
  "What rock band has four men who don't sing? Mount Rushmore.",
  "What do you get if you cross a sweet potato and jazz? A yam session.",
  "Why did the DJ go to the doctor? Because of a slipped disc.",
  "What did the drummer call his twin daughters? Anna One, Anna Two.",

  // Surprising facts
  "Listening to music triggers the same brain chemicals as eating chocolate or having a great conversation.",
  "The world's longest concert lasted 639 years. It started in 2001 and is still playing in a German church.",
  "Your heartbeat actually syncs to the tempo of the music you're listening to.",
  "The song 'Happy Birthday' was copyrighted until 2016, earning about $2 million a year in royalties.",
  "Cows produce more milk when listening to slow, calming music.",
  "Flowers grow faster when exposed to music. Apparently even plants have taste.",
  "Finland has more metal bands per capita than any other country in the world.",
  "The first music ever recorded was 'Au Clair de la Lune' in 1860.",
  "Music can help plants grow up to 20% faster.",
  "Monaco's national orchestra is bigger than its army.",
  "The shortest song ever recorded is 'You Suffer' by Napalm Death at 1.316 seconds.",
  "Spotify's most-skipped part of any song is the intro if it's longer than 20 seconds.",
  "There are more possible melodies than atoms in the observable universe.",
  "Babies can distinguish between different musical keys from just days old.",
  "A violin is made from over 70 individual pieces of wood.",
  "Playing music regularly can increase your IQ by up to 7 points.",
  "The vibrations from a bass guitar can physically move your hair.",
  "The 'millennial whoop' (woah-oh-oh) appears in hundreds of pop hits since 2010.",
  "Freddie Mercury's vocal range spanned four full octaves.",
  "The Stradivarius violin's unique sound may be due to a mini ice age that made denser wood.",
  "Earworms (songs stuck in your head) happen because your brain is trying to fill in gaps in the melody.",
  "NASA has sent music into space on the Voyager Golden Record, including Chuck Berry and Beethoven.",
  "Birds can actually sing in different regional dialects, just like human accents.",
  "The didgeridoo is one of the oldest instruments, dating back over 40,000 years.",
  "Professional musicians' brains are visibly different from non-musicians' on an MRI scan.",
  "Playing a musical instrument uses nearly every area of the brain simultaneously.",
  "The term 'rock and roll' was originally used as a nautical term for the motion of a ship.",
  "Music therapy can reduce anxiety by up to 65%, according to some studies.",
  "The kazoo was invented in the 1840s. Yes, someone invented it on purpose.",
  "An octopus has three hearts but zero ability to clap. Tough crowd.",
  "The longest guitar solo ever recorded lasted 24 hours and 55 minutes.",
  "Studies show dogs prefer reggae and soft rock over other genres.",

  // More puns & jokes
  "Why did the music note go to the doctor? Because it was feeling a bit flat.",
  "What's an avocado's favourite genre? Guac and roll.",
  "Why couldn't the athlete listen to her music? Because she broke the record.",
  "What do you call a group of killer whales playing instruments? An orca-stra.",
  "How do you make a bandstand? Take away their chairs.",
  "What do you call a cow with no legs? Ground beef. What if it's musical? A moo-sical flat.",
  "Why do bagpipe players walk when they play? To get away from the noise.",
  "I used to play piano by ear, but now I use my hands.",
  "What's a robot's favourite music genre? Heavy metal.",
  "Why did the DJ bring a ladder to the club? To reach the high notes.",
  "What's the musical version of a peanut butter sandwich? A jam session.",
  "Why couldn't the musician unlock the door? He had the wrong key.",
  "What's the best way to tune a fish? With its scales.",
  "What do you call a sleeping dinosaur playing the guitar? A dino-snore.",
  "Why don't scientists trust atoms? Because they make up everything, even lyrics.",
  "What instrument do dogs play? The subwoofer.",
  "What do you call a singing laptop? A Dell.",
  "Why was the piano teacher so good? She had the right key to success.",
  "What do you call a musical bee? A bee-flat.",
  "Why did the singer climb a ladder? To reach the high notes.",

  // More facts
  "Bob Marley's last words were 'Money can't buy life.'",
  "The longest officially released song is 'The Rise and Fall of Bossanova' at 13 hours and 23 minutes.",
  "Leo Fender, inventor of the Telecaster and Stratocaster, never learned to play guitar.",
  "The guitar solo in 'Hotel California' took the Eagles several months to perfect.",
  "Queen's 'Bohemian Rhapsody' was considered too long and too unconventional to be a hit.",
  "The most expensive musical instrument ever sold was a Stradivarius viola for $45 million.",
  "Jimi Hendrix couldn't read music.",
  "Elvis Presley never wrote any of his own songs.",
  "The Beatles used the word 'love' 613 times across all their songs.",
  "The iconic THX cinema sound was created by a computer programme and is technically a composition.",
  "Vinyl 'Record Store Day' started in 2007 and helped revive vinyl sales worldwide.",
  "The human voice is the only instrument that exists inside the body.",
  "Metallica has played on all seven continents, including Antarctica.",
  "The term 'music' comes from the Greek word 'mousike', meaning 'art of the Muses'.",
  "A 2013 study found that sad music actually makes most listeners feel better, not worse.",
  "Barry Manilow didn't write 'I Write the Songs.' Bruce Johnston of the Beach Boys did.",
  "The harmonica is the world's best-selling musical instrument.",
  "Mozart composed his first piece of music at age five.",
  "Cher's 'Believe' (1998) was the first major hit to use Auto-Tune as a deliberate effect.",
  "In 2015, astronaut Chris Hadfield recorded the first music video in space.",

  // Even more puns
  "Middle C walks into a bar and orders a drink. The bartender says, 'Sorry, we don't serve minors.'",
  "What do you call a beautiful woman on a trombonist's arm? A tattoo.",
  "What's the difference between a drummer and a savings bond? One of them will eventually mature and earn money.",
  "What did the guitar say to the musician? Pick on someone your own size.",
  "What's a golfer's favourite type of music? Swing.",
  "How many sopranos does it take to change a light bulb? One. She just holds it and the world revolves around her.",
  "What genre of music do wind turbines like? They're big fans of metal.",
  "Why did the opera singer go sailing? To hit the high Cs.",
  "What's a mummy's favourite genre? Wrap music.",
  "Why did the musician throw his watch out the window? He wanted to see time fly in 4/4.",

  // Final batch of facts
  "Music has been shown to help premature babies gain weight and leave the hospital sooner.",
  "The oldest known musical instrument is a 40,000-year-old flute made from a vulture bone.",
  "Listening to music while exercising can improve your performance by up to 15%.",
  "The 'Phantom of the Opera' is the longest-running show in Broadway history.",
  "Ghana has 'fantasy coffins' shaped like guitars and other instruments for musical funerals.",
  "In the 1980s, the US military used loud rock music as a psychological weapon during the Panama invasion.",
  "Frank Sinatra was once offered the lead role in 'Die Hard.' He turned it down.",
  "The first commercial CD pressed was ABBA's 'The Visitors' in 1982.",
  "Paul McCartney's 'Yesterday' has more cover versions than any other song in history.",
  "The longest drum roll ever lasted 12 hours and 5 minutes.",
  "The term 'album' originally referred to a collection of 78 RPM records stored together.",
  "Research shows learning an instrument as a child can delay the onset of dementia by up to 5 years.",
  "There are over 97 million songs on Spotify.",
  "A group of flamingos is called a 'flamboyance', which sounds like a jazz band name.",
  "Beethoven composed some of his most famous works while completely deaf.",
  "The acoustic guitar is the most popular instrument to learn in the UK.",
  "Your favourite song is probably your favourite because you associate it with an emotional event.",
  "The world's largest playable guitar is over 13 metres long.",
  "In Japan, there's a road that plays music when you drive over it at the right speed.",
  "The lullaby is one of the oldest musical forms, found in virtually every culture on earth.",
  "Music with a tempo of 60 BPM can synchronise with your brain's alpha waves, promoting calm.",
  "Some cheese makers play music to their cheese during ageing. They say it improves the flavour.",
  "The word 'choir' comes from the Greek 'choros', meaning a group of dancers or singers.",
  "Adele's '21' is the best-selling album of the 21st century.",
  "The first ever platinum record was awarded to the Eagles' 'Greatest Hits' in 1976.",
  "It takes about 10,000 hours of practice to master a musical instrument.",
  "Nessun Dorma translates to 'None Shall Sleep', which is ironic for a bedtime opera.",
  "The theremin is the only instrument you play without touching it.",
  "Your brain processes music 13 milliseconds faster than most other sounds.",
  "In ancient Greece, musicians were considered as important as athletes.",
]
